### ISSUE TITLE
Review an improvement plan for Bigquery operators

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#231]

**Comment by TobKed** [comment]
#### Sensors: 
`BigQueryTableSensor`
There  is just one sensor and its name follows naming convention. The sensor accepts reasonable parameters and uses `BigQueryHook` in proper way.
Uses deprecated `bigquery_conn_id` instead of `gcp_conn_id`.
**Proposition:** add `gcp_conn_id` parameter support, keep support for `bigquery_conn_id` parameters, add deprecation warning (keeping backward compatibility).

#### Operators:
##### Helper classes:
```
BigQueryConsoleLink
BigQueryConsoleIndexableLink
```
Helper classes for `operator_extra_links` property of `BigQueryOperator`.
**Proposition:** Nothing to be changed.

##### Check operators:
```
BigQueryCheckOperator
BigQueryValueCheckOperator
BigQueryIntervalCheckOperator
```
They seem to follow naming convention.
Use deprecated `bigquery_conn_id`, support for `gcp_conn_id` provided, deprecation warning is present.
Due to inheritance from `*CheckOperator` they are dependent on **conn->cursor** PEP-249 `BigQueryHook` implementation.
**Proposition:** TODO

##### Query operators:
```
BigQueryOperator
BigQueryCreateEmptyTableOperator
BigQueryCreateExternalTableOperator
BigQueryDeleteDatasetOperator
BigQueryCreateEmptyDatasetOperator
BigQueryGetDatasetOperator
BigQueryPatchDatasetOperator
BigQueryUpdateDatasetOperator
BigQueryTableDeleteOperator
```
Only `BigQueryOperator` does not follow naming convention.
In some places there is still `bigquery_conn_id` (when also other conn_id is used `google_cloud_storage_conn_id`)

**Proposition:**
* add `gcp_conn_id` where deprecated is still present, preserve backward compatibility and add deprecation warning
* rename `BigQueryOperator` to `BigQueryRunQueryOperator`

WIP

**Comment by TobKed** [comment]
cc @mik-laj @nuclearpinguin @potiuk

**Comment by nuclearpinguin** [comment]
> ### General questions:
> * Operator `BigQueryOperator` takes a lot of arguments which are passed to `BigQueryHook`. In the Google Library they create `google.cloud.bigquery.job.QueryJobConfig` object. When Google Library will be used these arguments will be used to instantiate config objects. Question is: are key-word arguments for hook could be deprecated and require config object as a parameter?
>   Similar situation situation is for `*TableOperator`s and `google.cloud.bigquery.table.Table` object. Or maybe it could be done in hooks instead of the operators? Should it be done at all?


I think BQ belongs to most used operators and we should preserve backward compatibility. There are two ways to approach this: build object from kwargs or keep key words arguments for time being and rise an error when "object" was not passed. Personally I prefer the second option as it's easier to remove something in future than add a "builder" now (that will be remove - time wasting).  I would suggest also adding "create_my_object" method for easier transfer between old and new approach.

Regarding Cursor - I think we should have two hook / operators. One for average users (implementing what python BQ clients has) and one for those who know what a cursor is. This should simplify the refactor.

**Comment by potiuk** [comment]
I agree that backwards compatibility is really important for BQ. 

My proposal is to only leave the QueryJobConfig object as parameter and if it is missing, use builder that can be applied to kwargs (raising deprecation warning).

We should be able to pass both the `google.cloud.bigquery.job.QueryJobConfig` class as well as dict representation (I think it should be possible). The latter will allow to use templates in backwards-compatible way. 

We could also think about implementing template handling for QueryJobConfig-like object (if it does not work like that for now).

We can vote on those approaches when everyone chimes in :). I can be convinced otherwise.

For the cursor - I think indeed it should be separated out.

**Comment by nuclearpinguin** [comment]
Is it done? @TobKed

**Comment by TobKed** [comment]
@nuclearpinguin, not yet, to do this I am working on https://github.com/PolideaInternal/airflow/issues/126 with with @mik-laj to be sure that nothing is broken when any changes will be introduced.
