### ISSUE TITLE
Remove deprecation warning 

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#246]
```
opt/airflow/airflow/contrib/hooks/gcp_sql_hook.py:30: DeprecationWarning: This module is deprecated. Please use `airflow.gcp.hooks.cloud_sql`
  DeprecationWarning,
```

**Comment by nuclearpinguin** [comment]
Why should we remove it?

**Comment by mik-laj** [comment]
Oh. I have not posted enough information. I don't want to clear the warning completely. I would like a warning not appear when I run tests.

**Comment by mik-laj** [comment]
I think that it is enough to delete references to the old package and then a warning will not appear.

**Comment by nuclearpinguin** [comment]
I agree with @mik-laj that we should remove / fix imports instead of suppressing warnings.

However I made a quick googling I nose does not seem to support such feature easily. Moreover I started to think why we are using nose? Is there any reason why not use more popular and better documented pytest? Btw. pytests enables easily filtering of warnings:
https://docs.pytest.org/en/latest/warnings.html

**Comment by potiuk** [comment]
The main reason we do not use pytest is that there was a problem with test discovery (naming of the test cases). Ash already tried pytest and had some success with it. I think everyone would love to migrate to pytest. It could be a nice 'intro to communty' project if you run it

**Comment by mik-laj** [comment]
Will be addressed via pytest.
