### ISSUE TITLE
Failed tasks when scaling composer

### ISSUE THREAD

**Issue by nuclearpinguin** [PolideaInternal/airflow#540]

**Comment by nuclearpinguin** [comment]
After a discussion with @mik-laj it seems that there's one problematic scenario when task was executed but will be tried for a next execution. Here are probably cases:

✅ send task > msg ack SUCCESS > execute SUCCESS
✅ send task > msg ack SUCCESS > execute FAILED
✅ send task > execute SUCCESS > msg ack SUCCESS (ack late)
✅ send task > execute FAILED > msg ack FAILED  (ack late)
❌ send task > execute SUCCESS > msg ack FAILED  (ack late)



In cases 1-3, the task is removed from a queue and is properly executed in Airflow (fail or SUCCESS no matter). In case 4, task will be rescheduled and the second execution will fail too because state FAILED (set by first execution) will not be proper state for execution. So, no harm done.

In case 5, task is executed and marked as SUCCESS in Airflow, however the msg is still in a queue (because of ack fail), thus a worker will try to consume it one more time. And then the second execution of the task will change it state to FAILED because state SUCCESS (set by first execution) is not a proper state for execution. This change of state is harmful because something was done (like dumping data) but Airflow will treat this as not done. 

Other cases like ack msg and no task execution are not as problematic because the task's state will be set to failed due to time out.

The solution to case 5 seems to make worker to ignore already executed tasks.

**Comment by nuclearpinguin** [comment]
@potiuk @mik-laj WDYT?

**Comment by potiuk** [comment]
I am not sure it's a huge problem. By definition all tasks of airflow are idempotent so there is no harm in doing something the second time (other than time needed). It's one of the reason why we insist so much on the idempotency of the tasks.

Note that checking the state at sending task time does not solve all the problems. There is also another case - probably rare but possible - race condition due to parallelism of execution. We can hit the case when ack failed, task succeeded but it has not yet recorded the state in the database and we retry it in the meantime (and state is recorded just after we sent retry task).

This is the scenario:

send_task -> execute SUCCESS (but status not yet recorded in the DB - in progress) -> msg ack Failed() -> start_retrying (checked status in the DB)  -> (executing tasks records SUCCESS in the DB) -> retrying

Not sure if we can do anything about that one though (and whether it is needed due to idempotency of Airflow tasks) . 
The only thing that comes to my mind is to double-check the status at execution time by the executing task (not by the sender) - so do what you described in 5. but on the receiving side. 

So if we run the task and find that state is set to success, we should immediately finish with state = SUCCESS. Maybe that's a better solution ?

**Comment by nuclearpinguin** [comment]
> I am not sure it's a huge problem. By definition all tasks of airflow are idempotent so there is no harm in doing something the second time (other than time needed). It's one of the reason why we insist so much on the idempotency of the tasks.
> 

Idempotency is not a problem here (at least not main problem). The problem is that airflow changes state of already executed task and that in my opinion is wrong. 

Whole schedule - execute cycle has completed and task A is SUCCESS. But then it happens that message "hey execute task A" is still in queue (due to some error). And because worker is "dumb" he takes the task because "whoa, here's something I have to consume". And he tries to consume but he can't so he changes the state of A to FAILED. 

The proper scenario in for this case assumes that worker is smart and do "whoa, here's something I have to consume but I already did that, so I will just acknowledge it". No state change.

> So if we run the task and find that state is set to success, we should immediately finish with state = SUCCESS. Maybe that's a better solution ?

That would required some change to TI deps checks. On the other hand we can implement "custom pre-check" that will be run by worker before execution.
